In [1]:
from dx_client import DXClient, DXClientConfig
from dx_client.cache import DuckDBCache

from typing import List
import numpy as np

import dotenv
dotenv.load_dotenv('../../.env')

True

In [2]:
cacheInstance = DuckDBCache()
config = DXClientConfig(
    
)
client =DXClient(config=config, cache=cacheInstance)
client.connect()

In [3]:
dd = client.get_data_dictionary(refresh=False)

In [4]:
# 1. search hypertension related fields


# 在 title、folder_path、description 中搜索
htn = dd[
    dd['title'].str.lower().str.contains('hypertension|blood pressure|systolic|diastolic', na=False) |
    dd['folder_path'].str.lower().str.contains('hypertension|blood.pressure', na=False)
]

htn
# htn[['entity', 'name', 'title', 'type', 'folder_path', 'coding_name']].to_string()

,entity,name,type,primary_key_type,title,description,coding_name,concept,folder_path,is_multi_select,is_sparse_coding,linkout,longitudinal_axis_type,referenced_entity_field,relationship,units
32,participant,p36_i0,string,,Blood pressure device ID | Instance 0,None,,None,Assessment centre/Physical measures/Blood pres...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
33,participant,p36_i1,string,,Blood pressure device ID | Instance 1,None,,None,Assessment centre/Physical measures/Blood pres...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
34,participant,p36_i2,string,,Blood pressure device ID | Instance 2,None,,None,Assessment centre/Physical measures/Blood pres...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
35,participant,p36_i3,string,,Blood pressure device ID | Instance 3,None,,None,Assessment centre/Physical measures/Blood pres...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
36,participant,p37_i0,string,,Blood pressure manual sphygmomanometer device ...,None,,None,Assessment centre/Physical measures/Blood pres...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32221,participant,p132187,integer,,Source of report of O13 (gestational [pregnanc...,None,data_coding_2171,None,Health-related outcomes/First occurrences/Preg...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
32222,participant,p132188,date,,Date O14 first reported (gestational [pregnanc...,None,data_coding_819,None,Health-related outcomes/First occurrences/Preg...,False,True,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
32223,participant,p132189,integer,,Source of report of O14 (gestational [pregnanc...,None,data_coding_2171,None,Health-related outcomes/First occurrences/Preg...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
32226,participant,p132192,date,,Date O16 first reported (unspecified maternal ...,None,data_coding_819,None,Health-related outcomes/First occurrences/Preg...,False,True,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
32227,participant,p132193,integer,,Source of report of O16 (unspecified maternal ...,None,data_coding_2171,None,Health-related outcomes/First occurrences/Preg...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN

In [5]:
proteome = dd[dd['entity'].str.contains(r'olink_*')]
proteome_fields = proteome['entity'] + '.' + proteome['name']

proteome_fields

32803       olink_instance_0.eid
32804      olink_instance_0.a1bg
32805     olink_instance_0.aamdc
32806    olink_instance_0.aarsd1
32807     olink_instance_0.abca2
                  ...
38650     olink_instance_3.xrcc4
38651      olink_instance_3.yes1
38652    olink_instance_3.ythdf3
38653    olink_instance_3.zbtb16
38654    olink_instance_3.zbtb17
Length: 5852, dtype: str

In [6]:
# cohort = client.create_cohort(name='auto_cohort', entity_fields=['olink_instance_0$A1BG', 'participant$p132601'], filters = {
#     "logic": "and",
#     "pheno_filters": {
#         "logic": "and",
#         "compound": [
#             {
#                 "name": "phenotype",
#                 "logic": "and",
#                 "filters": {
#                     # 字段名 → 条件列表
#                     "participant$p30903_i0": [
#                         {"condition": "between", "values": [0, 2]}
#                     ]
#                 }
#             }
#         ]
#     }
# })

In [7]:
dd[dd['entity'].str.contains('olink')]

,entity,name,type,primary_key_type,title,description,coding_name,concept,folder_path,is_multi_select,is_sparse_coding,linkout,longitudinal_axis_type,referenced_entity_field,relationship,units
32803,olink_instance_0,eid,string,primary_key,Participant ID,None,,None,,False,False,NaN,None,,,NaN
32804,olink_instance_0,a1bg,double,,A1BG;Alpha-1B-glycoprotein,None,,None,,False,False,NaN,None,,,NaN
32805,olink_instance_0,aamdc,double,,AAMDC;Mth938 domain-containing protein,None,,None,,False,False,NaN,None,,,NaN
32806,olink_instance_0,aarsd1,double,,AARSD1;Alanyl-tRNA editing protein Aarsd1,None,,None,,False,False,NaN,None,,,NaN
32807,olink_instance_0,abca2,double,,ABCA2;ATP-binding cassette sub-family A member 2,None,,None,,False,False,NaN,None,,,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38650,olink_instance_3,xrcc4,double,,XRCC4;DNA repair protein XRCC4,None,,None,,False,False,NaN,None,,,NaN
38651,olink_instance_3,yes1,double,,YES1;Tyrosine-protein kinase Yes,None,,None,,False,False,NaN,None,,,NaN
38652,olink_instance_3,ythdf3,double,,YTHDF3;YTH domain-containing family protein 3,None,,None,,False,False,NaN,None,,,NaN
38653,olink_instance_3,zbtb16,double,,ZBTB16;Zinc finger and BTB domain-containing p...,None,,None,,False,False,NaN,None,,,NaN
38654,olink_instance_3,zbtb17,double,,ZBTB17;Zinc finger and BTB domain-containing p...,None,,None,,False,False,NaN,None,,,NaN

In [10]:
# 下载完整的olink数据
# 存在的问题：直接将所有column放进来会导致最终得到的df为空，需要分为多块进行整合。然而UKB有提到eid在不同的application数据获取之间会变化，这种切分方法也存在着潜在问题。
# 关于这一点，我需要进行主动测试。eid的变动会造成cohort的合并错误，计划通过比对两次cohort的合并结果是否一致来进行验证
# 更新：正确的方法应该是回避直接的数据下载，最简单的方法是使用cli的extract_table (应该也有对应的API，目前先实现数据提取)，导出数据后通过启动Workstation进行分析（也许可以下载到本地）


olink_cohort_set = dd[dd['entity'].str.contains(r'olink_.*0')]
olink_fields = olink_cohort_set['entity'] + '$' + olink_cohort_set['name']

olink0_cohort = client.create_cohort('olink_cohort_1', entity_fields=olink_fields.tolist()[:500], filters={}, folder="/")

In [11]:
olink0_cohort

DXCohortInfo(id='record-J7GB8ZQJj70b37Bf5z7Bjpvz', name='olink_cohort_1', project='project-J3Y7p9jJj70gKV8XKv2yxqv5', folder='/', state='', description='', created=0, modified=0, participant_count=0, entity_fields=['olink_instance_0$eid', 'olink_instance_0$a1bg', 'olink_instance_0$aamdc', 'olink_instance_0$aarsd1', 'olink_instance_0$abca2', 'olink_instance_0$abhd14b', 'olink_instance_0$abl1', 'olink_instance_0$abo', 'olink_instance_0$abraxas2', 'olink_instance_0$acaa1', 'olink_instance_0$acadm', 'olink_instance_0$acadsb', 'olink_instance_0$acan', 'olink_instance_0$ace', 'olink_instance_0$ace2', 'olink_instance_0$ache', 'olink_instance_0$acot13', 'olink_instance_0$acox1', 'olink_instance_0$acp1', 'olink_instance_0$acp5', 'olink_instance_0$acp6', 'olink_instance_0$acrbp', 'olink_instance_0$acrv1', 'olink_instance_0$acsl1', 'olink_instance_0$acta2', 'olink_instance_0$actn2', 'olink_instance_0$actn4', 'olink_instance_0$acvrl1', 'olink_instance_0$acy1', 'olink_instance_0$acy3', 'olink_instance_0$acyp1', 'olink_instance_0$ada', 'olink_instance_0$ada2', 'olink_instance_0$adam12', 'olink_instance_0$adam15', 'olink_instance_0$adam22', 'olink_instance_0$adam23', 'olink_instance_0$adam8', 'olink_instance_0$adam9', 'olink_instance_0$adamts1', 'olink_instance_0$adamts13', 'olink_instance_0$adamts15', 'olink_instance_0$adamts16', 'olink_instance_0$adamts4', 'olink_instance_0$adamts8', 'olink_instance_0$adamtsl2', 'olink_instance_0$adamtsl4', 'olink_instance_0$adamtsl5', 'olink_instance_0$adcyap1r1', 'olink_instance_0$add1', 'olink_instance_0$adgrb3', 'olink_instance_0$adgrd1', 'olink_instance_0$adgre1', 'olink_instance_0$adgre2', 'olink_instance_0$adgre5', 'olink_instance_0$adgrf5', 'olink_instance_0$adgrg1', 'olink_instance_0$adgrg2', 'olink_instance_0$adgrv1', 'olink_instance_0$adh1b', 'olink_instance_0$adh4', 'olink_instance_0$adipoq', 'olink_instance_0$adm', 'olink_instance_0$adra2a', 'olink_instance_0$afap1', 'olink_instance_0$afm', 'olink_instance_0$afp', 'olink_instance_0$agbl2', 'olink_instance_0$ager', 'olink_instance_0$agr2', 'olink_instance_0$agr3', 'olink_instance_0$agrn', 'olink_instance_0$agrp', 'olink_instance_0$agt', 'olink_instance_0$agxt', 'olink_instance_0$ahcy', 'olink_instance_0$ahnak', 'olink_instance_0$ahnak2', 'olink_instance_0$ahsa1', 'olink_instance_0$ahsg', 'olink_instance_0$ahsp', 'olink_instance_0$aida', 'olink_instance_0$aif1', 'olink_instance_0$aif1l', 'olink_instance_0$aifm1', 'olink_instance_0$ak1', 'olink_instance_0$ak2', 'olink_instance_0$akap12', 'olink_instance_0$akr1b1', 'olink_instance_0$akr1b10', 'olink_instance_0$akr1c4', 'olink_instance_0$akr7l', 'olink_instance_0$akt1s1', 'olink_instance_0$akt2', 'olink_instance_0$akt3', 'olink_instance_0$alcam', 'olink_instance_0$aldh1a1', 'olink_instance_0$aldh2', 'olink_instance_0$aldh3a1', 'olink_instance_0$aldh5a1', 'olink_instance_0$alms1', 'olink_instance_0$alpi', 'olink_instance_0$alpp', 'olink_instance_0$ambn', 'olink_instance_0$ambp', 'olink_instance_0$amdhd2', 'olink_instance_0$amfr', 'olink_instance_0$amigo1', 'olink_instance_0$amigo2', 'olink_instance_0$amn', 'olink_instance_0$amot', 'olink_instance_0$amotl2', 'olink_instance_0$ampd3', 'olink_instance_0$amy1a_amy1b_amy1c', 'olink_instance_0$amy2a', 'olink_instance_0$amy2b', 'olink_instance_0$ang', 'olink_instance_0$angpt1', 'olink_instance_0$angpt2', 'olink_instance_0$angptl1', 'olink_instance_0$angptl2', 'olink_instance_0$angptl3', 'olink_instance_0$angptl4', 'olink_instance_0$angptl7', 'olink_instance_0$ank2', 'olink_instance_0$ankmy2', 'olink_instance_0$ankra2', 'olink_instance_0$ankrd54', 'olink_instance_0$anp32c', 'olink_instance_0$anpep', 'olink_instance_0$anxa1', 'olink_instance_0$anxa10', 'olink_instance_0$anxa11', 'olink_instance_0$anxa2', 'olink_instance_0$anxa3', 'olink_instance_0$anxa4', 'olink_instance_0$anxa5', 'olink_instance_0$aoc1', 'olink_instance_0$aoc3', 'olink_instance_0$ap1g2', 'olink_instance_0$ap2b1', 'olink_instance_0$ap3b1', 'olink_instance_0$ap3s2', 'olink_instance_0$apbb1ip', 'olink_instance_0$apcs', 'olink_instance_0$apex1', 'olink_instance_0$aplp1', 'olink_instance_0$apoa1', 'olink_instance_0$apoa2', 'olink_instance_0$apoa4', 'olink_instance_0$apob', 'olink_instance_0$apobr', 'olink_instance_0$apoc1', 'olink_instance_0$apod', 'olink_instance_0$apoe', 'olink_instance_0$apof', 'olink_instance_0$apoh', 'olink_instance_0$apol1', 'olink_instance_0$apom', 'olink_instance_0$app', 'olink_instance_0$appl2', 'olink_instance_0$aprt', 'olink_instance_0$araf', 'olink_instance_0$areg', 'olink_instance_0$arf6', 'olink_instance_0$arfip1', 'olink_instance_0$arg1', 'olink_instance_0$arg2', 'olink_instance_0$arhgap1', 'olink_instance_0$arhgap25', 'olink_instance_0$arhgap30', 'olink_instance_0$arhgap45', 'olink_instance_0$arhgap5', 'olink_instance_0$arhgef1', 'olink_instance_0$arhgef10', 'olink_instance_0$arhgef12', 'olink_instance_0$arhgef5', 'olink_instance_0$arid3a', 'olink_instance_0$arid4b', 'olink_instance_0$arl13b', 'olink_instance_0$arl2bp', 'olink_instance_0$armcx2', 'olink_instance_0$arnt', 'olink_instance_0$arntl', 'olink_instance_0$arsa', 'olink_instance_0$arsb', 'olink_instance_0$art3', 'olink_instance_0$art5', 'olink_instance_0$artn', 'olink_instance_0$asah1', 'olink_instance_0$asah2', 'olink_instance_0$asgr1', 'olink_instance_0$asgr2', 'olink_instance_0$aspn', 'olink_instance_0$aspscr1', 'olink_instance_0$asrgl1', 'olink_instance_0$ass1', 'olink_instance_0$atf2', 'olink_instance_0$atf4', 'olink_instance_0$atg16l1', 'olink_instance_0$atg4a', 'olink_instance_0$atox1', 'olink_instance_0$atp1b1', 'olink_instance_0$atp1b2', 'olink_instance_0$atp1b3', 'olink_instance_0$atp1b4', 'olink_instance_0$atp2b4', 'olink_instance_0$atp5f1d', 'olink_instance_0$atp5if1', 'olink_instance_0$atp5po', 'olink_instance_0$atp6ap2', 'olink_instance_0$atp6v1d', 'olink_instance_0$atp6v1f', 'olink_instance_0$atp6v1g1', 'olink_instance_0$atp6v1g2', 'olink_instance_0$atraid', 'olink_instance_0$atrn', 'olink_instance_0$atxn10', 'olink_instance_0$atxn2', 'olink_instance_0$atxn2l', 'olink_instance_0$atxn3', 'olink_instance_0$axin1', 'olink_instance_0$axl', 'olink_instance_0$azi2', 'olink_instance_0$azu1', 'olink_instance_0$b2m', 'olink_instance_0$b3gat3', 'olink_instance_0$b3gnt7', 'olink_instance_0$b4galt1', 'olink_instance_0$b4gat1', 'olink_instance_0$babam1', 'olink_instance_0$bach1', 'olink_instance_0$bag3', 'olink_instance_0$bag4', 'olink_instance_0$bag6', 'olink_instance_0$baiap2', 'olink_instance_0$bambi', 'olink_instance_0$bank1', 'olink_instance_0$bap18', 'olink_instance_0$batf', 'olink_instance_0$bax', 'olink_instance_0$bcam', 'olink_instance_0$bcan', 'olink_instance_0$bcat1', 'olink_instance_0$bcat2', 'olink_instance_0$bche', 'olink_instance_0$bcl2', 'olink_instance_0$bcl2l1', 'olink_instance_0$bcl2l11', 'olink_instance_0$bcl2l15', 'olink_instance_0$bcl7a', 'olink_instance_0$bcl7b', 'olink_instance_0$bcr', 'olink_instance_0$bdnf', 'olink_instance_0$becn1', 'olink_instance_0$bex3', 'olink_instance_0$bglap', 'olink_instance_0$bgn', 'olink_instance_0$bhlhe40', 'olink_instance_0$bhmt2', 'olink_instance_0$bid', 'olink_instance_0$bin2', 'olink_instance_0$birc2', 'olink_instance_0$blmh', 'olink_instance_0$blnk', 'olink_instance_0$bloc1s2', 'olink_instance_0$bloc1s3', 'olink_instance_0$blvrb', 'olink_instance_0$bmp10', 'olink_instance_0$bmp4', 'olink_instance_0$bmp6', 'olink_instance_0$bmper', 'olink_instance_0$bnip2', 'olink_instance_0$bnip3l', 'olink_instance_0$boc', 'olink_instance_0$bola1', 'olink_instance_0$bola2_bola2b', 'olink_instance_0$bpifa2', 'olink_instance_0$bpifb1', 'olink_instance_0$bpifb2', 'olink_instance_0$brap', 'olink_instance_0$brd1', 'olink_instance_0$brd2', 'olink_instance_0$brd3', 'olink_instance_0$brdt', 'olink_instance_0$brk1', 'olink_instance_0$brme1', 'olink_instance_0$brsk2', 'olink_instance_0$bsg', 'olink_instance_0$bsnd', 'olink_instance_0$bst1', 'olink_instance_0$bst2', 'olink_instance_0$btc', 'olink_instance_0$btd', 'olink_instance_0$btla', 'olink_instance_0$btn1a1', 'olink_instance_0$btn2a1', 'olink_instance_0$btn3a2', 'olink_instance_0$btnl10', 'olink_instance_0$c19orf12', 'olink_instance_0$c1galt1c1', 'olink_instance_0$c1qa', 'olink_instance_0$c1qbp', 'olink_instance_0$c1ql2', 'olink_instance_0$c1qtnf1', 'olink_instance_0$c1qtnf5', 'olink_instance_0$c1qtnf6', 'olink_instance_0$c1qtnf9', 'olink_instance_0$c1r', 'olink_instance_0$c1rl', 'olink_instance_0$c1s', 'olink_instance_0$c2', 'olink_instance_0$c2cd2l', 'olink_instance_0$c2orf69', 'olink_instance_0$c3', 'olink_instance_0$c4bpb', 'olink_instance_0$c5', 'olink_instance_0$c7', 'olink_instance_0$c7orf50', 'olink_instance_0$c8b', 'olink_instance_0$c9', 'olink_instance_0$c9orf40', 'olink_instance_0$ca1', 'olink_instance_0$ca11', 'olink_instance_0$ca12', 'olink_instance_0$ca13', 'olink_instance_0$ca14', 'olink_instance_0$ca2', 'olink_instance_0$ca3', 'olink_instance_0$ca4', 'olink_instance_0$ca5a', 'olink_instance_0$ca6', 'olink_instance_0$ca7', 'olink_instance_0$ca8', 'olink_instance_0$ca9', 'olink_instance_0$cabp2', 'olink_instance_0$cacna1c', 'olink_instance_0$cacna1h', 'olink_instance_0$cacnb1', 'olink_instance_0$cacnb3', 'olink_instance_0$cacybp', 'olink_instance_0$cadps', 'olink_instance_0$calb1', 'olink_instance_0$calb2', 'olink_instance_0$calca', 'olink_instance_0$calcb', 'olink_instance_0$calcoco1', 'olink_instance_0$calcoco2', 'olink_instance_0$caly', 'olink_instance_0$camkk1', 'olink_instance_0$camlg', 'olink_instance_0$camsap1', 'olink_instance_0$cant1', 'olink_instance_0$capg', 'olink_instance_0$capn3', 'olink_instance_0$caps', 'olink_instance_0$carhsp1', 'olink_instance_0$casc3', 'olink_instance_0$casp1', 'olink_instance_0$casp10', 'olink_instance_0$casp2', 'olink_instance_0$casp3', 'olink_instance_0$casp4', 'olink_instance_0$casp7', 'olink_instance_0$casp8', 'olink_instance_0$casp9', 'olink_instance_0$casq2', 'olink_instance_0$cat', 'olink_instance_0$cblif', 'olink_instance_0$cbln1', 'olink_instance_0$cbln4', 'olink_instance_0$cbs', 'olink_instance_0$cbx2', 'olink_instance_0$cc2d1a', 'olink_instance_0$ccar2', 'olink_instance_0$ccdc134', 'olink_instance_0$ccdc28a', 'olink_instance_0$ccdc50', 'olink_instance_0$ccdc80', 'olink_instance_0$ccer2', 'olink_instance_0$ccl11', 'olink_instance_0$ccl13', 'olink_instance_0$ccl14', 'olink_instance_0$ccl15', 'olink_instance_0$ccl16', 'olink_instance_0$ccl17', 'olink_instance_0$ccl18', 'olink_instance_0$ccl19', 'olink_instance_0$ccl2', 'olink_instance_0$ccl20', 'olink_instance_0$ccl21', 'olink_instance_0$ccl22', 'olink_instance_0$ccl23', 'olink_instance_0$ccl24', 'olink_instance_0$ccl25', 'olink_instance_0$ccl26', 'olink_instance_0$ccl27', 'olink_instance_0$ccl28', 'olink_instance_0$ccl3', 'olink_instance_0$ccl4', 'olink_instance_0$ccl5', 'olink_instance_0$ccl7', 'olink_instance_0$ccl8', 'olink_instance_0$ccn1', 'olink_instance_0$ccn2', 'olink_instance_0$ccn3', 'olink_instance_0$ccn4', 'olink_instance_0$ccn5', 'olink_instance_0$ccnd2', 'olink_instance_0$ccne1', 'olink_instance_0$ccs', 'olink_instance_0$cct5', 'olink_instance_0$cd101', 'olink_instance_0$cd109', 'olink_instance_0$cd14', 'olink_instance_0$cd160', 'olink_instance_0$cd163', 'olink_instance_0$cd164', 'olink_instance_0$cd164l2', 'olink_instance_0$cd177', 'olink_instance_0$cd1c', 'olink_instance_0$cd2', 'olink_instance_0$cd200', 'olink_instance_0$cd200r1', 'olink_instance_0$cd207', 'olink_instance_0$cd209', 'olink_instance_0$cd22', 'olink_instance_0$cd226', 'olink_instance_0$cd244', 'olink_instance_0$cd248', 'olink_instance_0$cd27', 'olink_instance_0$cd274', 'olink_instance_0$cd276', 'olink_instance_0$cd28', 'olink_instance_0$cd2ap', 'olink_instance_0$cd300a', 'olink_instance_0$cd300c', 'olink_instance_0$cd300e', 'olink_instance_0$cd300lf', 'olink_instance_0$cd300lg', 'olink_instance_0$cd302', 'olink_instance_0$cd33', 'olink_instance_0$cd34', 'olink_instance_0$cd36', 'olink_instance_0$cd38', 'olink_instance_0$cd3d', 'olink_instance_0$cd3e', 'olink_instance_0$cd3g', 'olink_instance_0$cd4', 'olink_instance_0$cd40', 'olink_instance_0$cd40lg', 'olink_instance_0$cd46', 'olink_instance_0$cd48', 'olink_instance_0$cd5', 'olink_instance_0$cd55', 'olink_instance_0$cd58', 'olink_instance_0$cd59', 'olink_instance_0$cd5l', 'olink_instance_0$cd6', 'olink_instance_0$cd63', 'olink_instance_0$cd69', 'olink_instance_0$cd7', 'olink_instance_0$cd70', 'olink_instance_0$cd72', 'olink_instance_0$cd74', 'olink_instance_0$cd79b', 'olink_instance_0$cd80', 'olink_instance_0$cd82', 'olink_instance_0$cd83', 'olink_instance_0$cd84', 'olink_instance_0$cd86', 'olink_instance_0$cd8a', 'olink_instance_0$cd93', 'olink_instance_0$cd99', 'olink_instance_0$cd99l2', 'olink_instance_0$cda', 'olink_instance_0$cdan1', 'olink_instance_0$cdc123', 'olink_instance_0$cdc25a', 'olink_instance_0$cdc26', 'olink_instance_0$cdc27', 'olink_instance_0$cdc37', 'olink_instance_0$cdc42bpb', 'olink_instance_0$cdcp1', 'olink_instance_0$cdh1', 'olink_instance_0$cdh15', 'olink_instance_0$cdh17', 'olink_instance_0$cdh2', 'olink_instance_0$cdh22', 'olink_instance_0$cdh23', 'olink_instance_0$cdh3', 'olink_instance_0$cdh4', 'olink_instance_0$cdh5', 'olink_instance_0$cdh6', 'olink_instance_0$cdhr1', 'olink_instance_0$cdhr2', 'olink_instance_0$cdhr5', 'olink_instance_0$cdk1', 'olink_instance_0$cdk5rap3', 'olink_instance_0$cdkl5'])

In [14]:
dd[dd['title'].str.contains('hypertension')]

,entity,name,type,primary_key_type,title,description,coding_name,concept,folder_path,is_multi_select,is_sparse_coding,linkout,longitudinal_axis_type,referenced_entity_field,relationship,units
20094,participant,p26244,double,,Standard PRS for hypertension (HT),None,,None,Genomics/Polygenic Risk Scores/Standard PRS,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,relative risk
20095,participant,p26245,double,,Enhanced PRS for hypertension (HT),None,,None,Genomics/Polygenic Risk Scores/Enhanced PRS,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,relative risk
31324,participant,p131286,date,,Date I10 first reported (essential (primary) h...,None,data_coding_819,None,Health-related outcomes/First occurrences/Circ...,False,True,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
31325,participant,p131287,integer,,Source of report of I10 (essential (primary) h...,None,data_coding_2171,None,Health-related outcomes/First occurrences/Circ...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
31332,participant,p131294,date,,Date I15 first reported (secondary hypertension),None,data_coding_819,None,Health-related outcomes/First occurrences/Circ...,False,True,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
31333,participant,p131295,integer,,Source of report of I15 (secondary hypertension),None,data_coding_2171,None,Health-related outcomes/First occurrences/Circ...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
32214,participant,p132180,date,,Date O10 first reported (pre-existing hyperten...,None,data_coding_819,None,Health-related outcomes/First occurrences/Preg...,False,True,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
32215,participant,p132181,integer,,Source of report of O10 (pre-existing hyperten...,None,data_coding_2171,None,Health-related outcomes/First occurrences/Preg...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
32218,participant,p132184,date,,Date O12 first reported (gestational [pregnanc...,None,data_coding_819,None,Health-related outcomes/First occurrences/Preg...,False,True,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
32219,participant,p132185,integer,,Source of report of O12 (gestational [pregnanc...,None,data_coding_2171,None,Health-related outcomes/First occurrences/Preg...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
32220,participant,p132186,date,,Date O13 first reported (gestational [pregnanc...,None,data_coding_819,None,Health-related outcomes/First occurrences/Preg...,False,True,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
32221,participant,p132187,integer,,Source of report of O13 (gestational [pregnanc...,None,data_coding_2171,None,Health-related outcomes/First occurrences/Preg...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
32222,participant,p132188,date,,Date O14 first reported (gestational [pregnanc...,None,data_coding_819,None,Health-related outcomes/First occurrences/Preg...,False,True,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
32223,participant,p132189,integer,,Source of report of O14 (gestational [pregnanc...,None,data_coding_2171,None,Health-related outcomes/First occurrences/Preg...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
32226,participant,p132192,date,,Date O16 first reported (unspecified maternal ...,None,data_coding_819,None,Health-related outcomes/First occurrences/Preg...,False,True,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN
32227,participant,p132193,integer,,Source of report of O16 (unspecified maternal ...,None,data_coding_2171,None,Health-related outcomes/First occurrences/Preg...,False,False,http://biobank.ctsu.ox.ac.uk/crystal/field.cgi...,None,,,NaN